version: "3"
services:
  app:
    container_name: notifications_service
    restart: always
    build: .
    env_file: .env
    ports:
      - "80:5000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
